---
title: "ggsci"
author:
  - 杨洪冰
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
---

## ggsci包学习

首先安装并加载相关包：

```{r}
library(ggsci)
library(ggplot2)
library(patchwork)
```

### 离散型调色板

载入数据：

```{r}
data("diamonds")
head(diamonds)
```

观察原始配色：

```{r}
p1 <- ggplot(subset(diamonds, carat >=2.2),
       aes(x = table, y = price, color = cut))+
  geom_point(alpha = 0.7)+
  geom_smooth(method = "loess", alpha = 0.05, size = 1, span = 1) +
  theme_bw()
p2 <- ggplot(
  subset(diamonds, carat > 2.2 & depth > 55 & depth < 70), 
  aes(x = depth, fill = cut) 
) +
  geom_histogram(colour = "black", binwidth = 1, position = "dodge") +
  theme_bw() 
p1+p2
```

使用Nature配色：

```{r}
p1 <- p1 + scale_color_npg()
p2 <- p2 + scale_fill_npg()
p1+p2
```

AAAS配色：

```{r}
p1 <- p1 + scale_color_aaas()
p2 <- p2 + scale_fill_aaas()
p1+p2
```

新英格兰杂志：

```{r}
p1 <- p1 + scale_color_nejm()
p2 <- p2 + scale_fill_nejm()
p1+p2
```

柳叶刀：

```{r}
p1 <- p1 + scale_color_lancet()
p2 <- p2 + scale_fill_lancet()
p1+p2
```

美国医学会杂志：

```{r}
p1 <- p1 + scale_color_jama()
p2 <- p2 + scale_fill_jama()
p1+p2
```

临床肿瘤学杂志：

```{r}
p1 <- p1 + scale_color_jco()
p2 <- p2 + scale_fill_jco()
p1+p2
```

辛普森：

```{r}
p1 <- p1 + scale_color_simpsons()
p2 <- p2 + scale_fill_simpsons()
p1+p2
```

### 连续型调色板

用相关性热图表示：

```{r}
library(reshape2)
data(mtcars)
cor <- cor(unname(cbind(mtcars, mtcars, mtcars, mtcars)))
cor_melt <- melt(cor)
p3 <- ggplot(
  cor_melt,
  aes(x = Var1, y = Var2, fill = value)
) +
  geom_tile(colour = "black", size = 0.3) +
  theme_bw() +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  )
p3
```

GSEA

```{r}
p3_gsea <- p3 + scale_fill_gsea()
p3_gsea_inv <- p3 + scale_fill_gsea(reverse = TRUE)
p3_gsea + p3_gsea_inv
```
